export const HOME_ACTION_TYPES = {
  HOME_SET_ITEMS_START: "home/HOME_SET_ITEMS_START",
  HOME_SET_ITEMS_SUCCESS: "home/HOME_ITEMS_SUCCESS",
  HOME_SET_ITEMS_FAILED: "home/HOME_ITEMS_FAILED",
  HOME_FETCH_ITEMS_START: "home/HOME_FETCH_ITEMS_START",
  HOME_FETCH_ITEMS_SUCCESS: "home/HOME_FETCH_ITEMS_SUCCESS",
  HOME_FETCH_ITEMS_FAILED: "home/HOME_FETCH_ITEMS_FAILED",
};
