export const CART_ACTION_TYPES = {
  SET_IS_CART_OPEN: "SET_IS_CART_OPEN",
  SET_CART_ITEMS_START: "SET_CART_ITEMS_START",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  ADD_CART_ITEMS: "ADD_CART_ITEMS",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
};
