export const CATEGORIES_ACTION_TYPES = {
  ADD_CATEGORIES_ITEMS_START: "categories/ADD_CATEGORIES_ITEMS_START",

  UPDATE_AND_ADD_CATEGORIES_ITEMS_START:
    "categories/UPDATE_AND_ADD_CATEGORIES_ITEMS_START",
  UPDATE_AND_ADD_CATEGORIES_ITEMS_SUCCESS:
    "categories/UPDATE_AND_ADD_CATEGORIES_ITEMS_SUCCESS",
  UPDATE_AND_ADD_CATEGORIES_ITEMS_FAILED:
    "categories/UPDATE_AND_ADD_CATEGORIES_ITEMS_FAILED",
  FETCH_CATEGORIES_START: "categories/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categories/FETCH_CATEGORIES_FAILED",
};
